# telling tmux what my terminal can handle
set -as terminal-features "xterm*:cpr:RGB:hyperlinks"
set -g default-terminal "tmux-256color"

# scrollback
set -g history-limit 50000

# longer message display duration
set -g display-time 4000

# mouse support
set -g mouse on

# Focus events enabled for terminals that support them
set -g focus-events on

# notifs support (tmux 3.4+)
set -gq allow-passthrough all

# remap prefix
set-option -g prefix2 C-a
bind-key C-a send-prefix -2

# tmux settings reload
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# easier splitting
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# easier pane nav
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# theme
run-shell ~/.config/tmux/amp-theme.tmux

